andreafrancia.largefileviewer.Main Class Reference
andreafrancia.largefileviewer.Main Class Reference
Public Member Functions
Main (String filename)
Creates new form Main.
Static Public Member Functions
static void main (final String args[])
Private Member Functions
void initComponents ()
This method is called from within the constructor to initialize the form.
Private Attributes
javax.swing.JList fileList
javax.swing.JScrollPane jScrollPane1
Static Private Attributes
static Logger logger = Logger.getLogger(Main.class.getName())
Detailed Description
Definition at line 8 of file Main.java.
Constructor & Destructor Documentation
andreafrancia.largefileviewer.Main.Main (String filename)
Creates new form Main.
Parameters:
filename
Definition at line 15 of file Main.java.
References andreafrancia.largefileviewer.Main.fileList, andreafrancia.largefileviewer.Main.initComponents(), and andreafrancia.largefileviewer.Main.logger.
Referenced by andreafrancia.largefileviewer.Main.main().
{
        initComponents();
        fileList.setFixedCellHeight(13);
        fileList.setFixedCellWidth(1);
        try {
            fileList.setModel(new LazyFileListModel(new File(filename)));
        } catch (FileNotFoundException ex) {
            logger.log(Level.SEVERE, null, ex);
        }
    }
Member Function Documentation
void andreafrancia.largefileviewer.Main.initComponents () [private]
This method is called from within the constructor to initialize the form.
WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
Definition at line 32 of file Main.java.
References andreafrancia.largefileviewer.Main.fileList, and andreafrancia.largefileviewer.Main.jScrollPane1.
Referenced by andreafrancia.largefileviewer.Main.Main().
{
        jScrollPane1 = new javax.swing.JScrollPane();
        fileList = new javax.swing.JList();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jScrollPane1.setViewportView(fileList);
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
static void andreafrancia.largefileviewer.Main.main (final String args[]) [static]
Parameters:
args the command line arguments
Definition at line 64 of file Main.java.
References andreafrancia.largefileviewer.Main.Main().
{
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String filename = args.length == 0 ? "test-file.txt" : args[0];
                new Main(filename).setVisible(true);
            }
        });
    }
Member Data Documentation
Logger andreafrancia.largefileviewer.Main.logger = Logger.getLogger(Main.class.getName()) [static, private]
Definition at line 10 of file Main.java.
Referenced by andreafrancia.largefileviewer.Main.Main().
javax.swing.JList andreafrancia.largefileviewer.Main.fileList [private]
Definition at line 74 of file Main.java.
Referenced by andreafrancia.largefileviewer.Main.initComponents(), and andreafrancia.largefileviewer.Main.Main().
javax.swing.JScrollPane andreafrancia.largefileviewer.Main.jScrollPane1 [private]
Definition at line 75 of file Main.java.
Referenced by andreafrancia.largefileviewer.Main.initComponents().
The documentation for this class was generated from the following file:
andreafrancia/largefileviewer/Main.java