#!/bin/bash
set -o xtrace

if [ ! -d _site/.git ]; then
    git clone --local . _site
    ( cd _site; git checkout master; )
fi

bundle exec jekyll build --safe
( cd _site; git add --all; git commit -m "Generated"; git push; )
git push --all origin
